---
- name: Check if rustup exists
  stat:
    path: /usr/bin/rustup
  register: rustup_installed

- block:
  - name: Install {{ toolchain }} toolchain
    command: 'rustup install {{ toolchain }}'

  - name: Set {{ toolchain }} toolchain
    command: 'rustup default {{ toolchain }}'

  - name: Install rustup components
    command: 'rustup component add {{ item }}'
    with_items: '{{ components }}'

  when: rustup_installed.stat.executable is defined and rustup_installed.stat.executable
