---
- name: Check if rustup exists
  stat:
    path: /usr/bin/rustup
  register: rustup_installed

- block:
  - name: Install {{ rust_toolchain }} toolchain
    command: 'rustup install {{ rust_toolchain }}'

  - name: Set {{ rust_toolchain }} toolchain
    command: 'rustup default {{ rust_toolchain }}'

  - name: Install rustup components
    command: 'rustup component add {{ item }}'
    with_items: '{{ rust_components }}'

  when: rustup_installed.stat.executable is defined and rustup_installed.stat.executable
