---
- name: Configure pacman
  lineinfile:
    path: /etc/pacman.conf
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
  with_items: '{{ pacman_options }}'
  become: yes

- name: Configure makepkg
  lineinfile:
    path: /etc/makepkg.conf
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
  with_items: '{{ makepkg_options }}'
  become: yes
