---
- name: 'Include OS-family specific variables for {{ ansible_os_family }}'
  include_vars: '{{ var_file }}'
  with_first_found:
      - files:
          - "vars/{{ ansible_os_family | lower }}-based.yml"
        errors: ignore
  loop_control:
    loop_var: var_file

- name: 'Include OS-family specific tasks for {{ ansible_os_family }}'
  include_tasks: '{{ task_file }}'
  with_first_found:
      - files:
          - "tasks/{{ ansible_os_family | lower }}-based.yml"
        errors: ignore
  loop_control:
    loop_var: task_file

- name: 'Include distribution specific variables for {{ ansible_distribution }}'
  include_vars: '{{ var_file }}'
  with_first_found:
      - files:
          - "vars/{{ ansible_distribution | lower }}.yml"
          - "vars/{{ ansible_os_family | lower }}.yml"
        errors: ignore
  loop_control:
    loop_var: var_file

- name: 'Include distribution specific tasks for {{ ansible_distribution }}'
  include_tasks: '{{ task_file }}'
  with_first_found:
      - files:
          - "tasks/{{ ansible_distribution | lower }}.yml"
          - "tasks/{{ ansible_os_family | lower }}.yml"
        errors: ignore
  loop_control:
    loop_var: task_file
