---
- name: Get current pacman branch
  command: pacman-mirrors --get-branch
  register: current_pacman_branch
  changed_when: False

- name: Configure pacman branch
  command: pacman-mirrors --api --set-branch {{ pacman_branch }}
  when: 'pacman_branch not in current_pacman_branch.stdout'
  become: yes
