Host *
    AddKeysToAgent yes
    ForwardAgent yes
    HostKeyAlgorithms +ssh-dss

Host ghost
    User root
    HostName 198.18.132.36

Host gitsource
    Hostname git.source.akamai.com
    Port 7999

Host gitsource-mirror
    Hostname quincy.mirror.git.source.akamai.com
    Port 7999

Host vm
    User jswierk
    HostName muc-lhvpwd.munich.corp.akamai.com

Host vm-ip
    User jswierk
    HostName 100.78.0.30
