#!/bin/sh

if [ -f /etc/os-release ]; then
  . /etc/os-release
  if [ -z "${ID_LIKE-}" ]; then
    ID_LIKE="${ID}"
  fi
  case "${ID_LIKE}" in
    arch)
      if [ ! -x /usr/bin/ansible ]; then
        sudo pacman -S --needed --noconfirm ansible || exit "$?"
      fi
      ;;
    *)
      echo "Unsupported Linux distribution: $ID"
      exit 1
      ;;
  esac
fi

printf '\nTo install everything run:\n'
cat <<'EOF'
ANSIBLE_HOME="$HOME/.config/ansible" \
CARGO_HOME="$HOME/.local/share/cargo" \
RUSTUP_HOME="$HOME/.local/share/rustup" \
ansible-playbook ansible/playbook.yml --ask-become-pass
EOF
