#!/bin/sh

if [ -f /etc/os-release ]; then
  . /etc/os-release
  if [ -z "${ID_LIKE-}" ]; then
    ID_LIKE="${ID}"
  fi
  case "${ID_LIKE}" in
    arch)
      if [ ! -x /usr/bin/ansible ]; then
        sudo pacman -S --needed --noconfirm ansible
      fi
      ;;
    *)
      echo "Unsupported Linux distribution: $ID"
      exit 1
      ;;
  esac
fi

export ANSIBLE_HOME="${HOME}/.config/ansible"
export CARGO_HOME="${HOME}/.local/share/cargo"
export RUSTUP_HOME="${HOME}/.local/share/rustup"

echo ""
echo "To install everything run:"
echo "$ ansible-playbook ansible/playbook.yml --ask-become-pass"
