---
dotfiles:
  - config/aspell/aspell.conf
  - config/atuin/config.toml
  - config/bat/config
  - config/btop/btop.conf
  - config/ccache/ccache.conf
  - config/clangd/config.yaml
  - config/emacs/early-init.el
  - config/emacs/init.el
  - config/emacs/versions.el
  - config/fish/config.fish
  - config/fish/fish_plugins
  - config/gdb/libstdcxx
  - config/gdb/libcxx
  - config/gdb-dashboard/config
  - config/git/attributes
  - config/git/config
  - config/git/config-delta
  - config/git/config-local
  - config/git/ignore
  - config/keepassxc/keepassxc.ini
  - config/kitty/kitty.conf
  - config/kitty/themes
  - config/lsd/config.yaml
  - config/mpv/input.conf
  - config/mpv/mpv.conf
  - config/ripgrep/config
  - config/sccache/config
  - config/yazi/yazi.toml
  - local/share/cargo/config.toml
  - ssh/config

dotdirs:
  - local/share/gdb
