[user]
name = "Jacek Swierk"
email = "jswierk@akamai.com"

[ui]
default-command = "log"
diff-editor = ":builtin"
pager = "delta"

[ui.diff]
format = "git"

[merge-tools.mergiraf]
program = "mergiraf"
merge-args = ["merge", "$base", "$left", "$right", "-o", "$output", "-l", "$marker_length", "--fast"]
merge-conflict-exit-codes = [1]

[merge-tools.ediff]
program = "sh"
merge-args = ['-c',
  'emacsclient -c --eval "(ediff-merge-files-with-ancestor \"$0\" \"$1\" \"$2\" nil \"$3\")"',
  '$left', '$right', '$base', '$output']

[template-aliases]
'format_timestamp(ts)' = "ts.ago()"

[templates]
draft_commit_description = '''
concat(
  description,
  "\n",
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[git]
push-new-bookmarks = true
