# Set XDG dir vars locally.
xdg_config_home="${HOME}/.config"
xdg_cache_home="${HOME}/.cache"
xdg_data_home="${HOME}/.local/share"
xdg_state_home="${HOME}/.local/state"

# Input Method framework.
export XMODIFIERS=@im=fcitx

# Partial XDG support that needs some help.
export ANSIBLE_HOME="${xdg_config_home}/ansible"
export ASPELL_CONF="home-dir ${xdg_config_home}/aspell/; per-conf aspell.conf"
export CARGO_HOME="${xdg_data_home}/cargo"
export GNUPGHOME="${xdg_data_home}/gnupg"
export GTK2_RC_FILES="${xdg_config_home}/gtk-2.0/settings.ini"
export RIPGREP_CONFIG_PATH="${xdg_config_home}/ripgrep/config"
export RUSTUP_HOME="${xdg_data_home}/rustup"

unset -v xdg_config_home
unset -v xdg_cache_home
unset -v xdg_data_home
unset -v xdg_state_home
