# Set XDG dir vars locally.
xdg_config_home="${HOME}/.config"
xdg_cache_home="${HOME}/.cache"
xdg_data_home="${HOME}/.local/share"
xdg_state_home="${HOME}/.local/state"

# Input Method framework.
export XMODIFIERS=@im=fcitx

# Partial XDG support that needs some help.
export ANSIBLE_HOME="${xdg_config_home}/ansible"
export ASPELL_CONF="home-dir ${xdg_config_home}/aspell/; per-conf aspell.conf"
export BUNDLE_USER_CONFIG="${xdg_config_home}/bundle"
export BUNDLE_USER_CACHE="${xdg_cache_home}/bundle"
export BUNDLE_USER_PLUGIN="${xdg_data_home}/bundle"
export CARGO_HOME="${xdg_data_home}/cargo"
export DOCKER_CONFIG="${xdg_config_home}/docker"
export GEM_HOME="${xdg_data_home}/gem"
export GEM_SPEC_CACHE="${xdg_cache_home}/gem"
export GNUPGHOME="${xdg_data_home}/gnupg"
export GTK2_RC_FILES="${xdg_config_home}/gtk-2.0/settings.ini"
export RIPGREP_CONFIG_PATH="${xdg_config_home}/ripgrep/config"
export RUSTUP_HOME="${xdg_data_home}/rustup"
export _ZO_DATA_DIR="${xdg_data_home}/zoxide"

# Needed by cargo to build Stormcloud.
export AKAMILL_INSTALL_PATH="/opt/akamill"
export BUILD_OS=alsi22
export OPENSSL_DIR="/opt/akamill"
export OPENSSL_INSTALL_PATH="${OPENSSL_DIR}"
export LD_LIBRARY_PATH="${OPENSSL_INSTALL_PATH}/lib:${LD_LIBRARY_PATH}"

unset -v xdg_config_home
unset -v xdg_cache_home
unset -v xdg_data_home
unset -v xdg_state_home
