---
- name: Download sublimehq-pub.gpg
  get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /tmp/

- name: Add sublimehq-pub.gpg to pacman
  command: pacman-key --add /tmp/sublimehq-pub.gpg
  become: yes

- name: Locally sign the specified keyid
  command: pacman-key --lsign-key 8A8F901A
  become: yes

- name: Remove downloaded sublimehq-pub.gpg
  file:
    path: /tmp/sublimehq-pub.gpg
    state: absent

- name: Add sublime-text repositories to pacman
  ini_file:
    path: /etc/pacman.conf
    section: sublime-text
    option: Server
    value: https://download.sublimetext.com/arch/stable/x86_64
  become: yes

- name: Install sublime-text
  pacman:
    name: sublime-text
    state: latest
    update_cache: yes
  become: yes

- name: Create folder for Package Control.sublime-package
  file:
    path: '{{ home_dir }}/.config/sublime-text-3/Installed Packages'
    state: directory

- name: Download Package Control.sublime-package
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: '{{ home_dir }}/.config/sublime-text-3/Installed Packages/Package Control.sublime-package'
