;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-symbol
        beginning-of-visual-line
        comment-dwim-2
        easy-kill
        electric-pair-delete-pair
        end-of-visual-line
        forward-symbol
        hungry-delete-backward
        hungry-delete-forward
        keyboard-escape-quit
        kill-region
        kill-visual-line
        markdown-outdent-or-delete
        mwim-beginning
        mwim-end
        org-self-insert-command
        set-mark-command-dwim
        string-inflection-camelcase
        string-inflection-kebab-case
        string-inflection-lower-camelcase
        string-inflection-underscore
        string-inflection-upcase
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        mouse-set-region
        pixel-scroll-precision
        ))
