---
- name: 'Include distribution specific tasks for {{ ansible_distribution }}'
  include_tasks: '{{ task_file }}'
  with_first_found:
      - files:
          - "tasks/{{ ansible_distribution | lower }}.yml"
          - "tasks/{{ ansible_os_family | lower }}.yml"
        skip: true
  loop_control:
    loop_var: task_file
