set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_FIND_ROOT_PATH
  $ENV{TOOLCHAIN_SYSROOT_TARGET}
  $ENV{TOOLCHAIN_SYSROOT_NATIVE}
)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
