---
home_dir: '{{ ansible_env.HOME }}'
dotfiles_dir: '{{ home_dir }}/.dotfiles'

dotfiles_src: '{{ dotfiles_dir }}/home'
dotfiles_dst: '{{ home_dir }}'
dotfiles_distro_src: '{{ dotfiles_src }}/{{ ansible_os_family | lower }}'

with_packages: True
with_sublime_text: True
with_rust: False
