---
- name: Create folders for config files
  file:
    path: '{{ (dotfiles_dst + "/." + item) | dirname }}'
    state: directory
  with_items: '{{ dotfiles }}'

- name: Symlink config files
  file:
    path: '{{ dotfiles_dst }}/.{{ item }}'
    src: '{{ dotfiles_src }}/{{ item }}'
    state: link
    force: yes
  with_items: '{{ dotfiles }}'
