---
- block:
  - name: Create folders for config files
    file:
      path: '{{ (dotfiles_dst + "/." + dotfile) | dirname }}'
      state: directory
    loop: '{{ dotfiles | default([], true) }}'
    loop_control:
      loop_var: dotfile

  - name: Symlink config files
    file:
      path: '{{ dotfiles_dst }}/.{{ dotfile }}'
      src: '{{ dotfiles_src }}/{{ dotfile }}'
      state: link
      force: yes
    loop: '{{ dotfiles | default([], true) }}'
    loop_control:
      loop_var: dotfile

  when: dotfiles is defined

- name: 'Include distribution specific variables for {{ ansible_distribution }}'
  include_vars: '{{ var_file }}'
  with_first_found:
      - files:
          - "vars/{{ ansible_distribution | lower }}.yml"
          - "vars/{{ ansible_os_family | lower }}.yml"
        skip: true
  loop_control:
    loop_var: var_file

- block:
  - name: 'Create folders for config files for {{ ansible_distribution }}'
    file:
      path: '{{ (dotfiles_dst + "/." + dotfile) | dirname }}'
      state: directory
    loop: '{{ dotfiles_distro | default([], true) }}'
    loop_control:
      loop_var: dotfile

  - name: 'Symlink config files for {{ ansible_distribution }}'
    file:
      path: '{{ dotfiles_dst }}/.{{ dotfile }}'
      src: '{{ dotfiles_distro_src }}/{{ dotfile }}'
      state: link
      force: yes
    loop: '{{ dotfiles_distro | default([], true) }}'
    loop_control:
      loop_var: dotfile

  when: dotfiles_distro is defined
