---
- name: Check if preferred {{ login_shell }} is installed
  stat:
    path: '{{ login_shell }}'
  register: login_shell_installed

- name: Set default shell as {{ login_shell }}
  user:
    name: '{{ ansible_user_id }}'
    shell: '{{ login_shell }}'
  when: login_shell_installed.stat.exists
  become: yes
