[build]
default-target = "x86_64-unknown-linux-gnu"

[build.env]
passthrough = [
    "LOG_TO_CONSOLE",
    "RUST_BACKTRACE",
    "RUST_LOG",
]

[target.x86_64-unknown-linux-gnu]
image = "stormcloud-env:alsi11"
