---
- hosts: localhost
  vars_files:
    - vars/config.yml
  pre_tasks:
    - name: 'Overwrite ansible facts for Manjaro'
      set_fact:
        ansible_facts: '{{ ansible_facts | default({}) | combine({"distribution": "Manjaro"}) }}'
        ansible_distribution: 'Manjaro'
      when:
        - ansible_facts['os_family'] == 'Archlinux'
        - ansible_facts['lsb'].get('id') == 'ManjaroLinux'
      tags: always
  roles:
    - role: dotfiles
      tags: dotfiles

    - role: os-configure
      tags: [os, os-configure]

    - role: os-update
      tags: [os, os-update]

    - role: os-upgrade
      tags: [os, os-upgrade]

    - role: os-packages
      tags: [os, os-packages]

    - role: os-shell
      tags: [os, os-shell]

    - role: dev-sublime-text
      tags: [dev, dev-sublime-text]
      when: with_sublime_text | default(False)

    - role: dev-vscode-extensions
      tags: [dev, dev-vscode-extensions]
      when: with_vscode_extensions | default(False)

    - role: dev-rust
      tags: [dev, dev-rust]
      when: with_rust | default(False)
