---
- hosts: localhost
  vars_files:
    - vars/config.yml
  roles:
    - role: dotfiles
      tags: dotfiles

    - role: os-configure
      tags: [os, os-configure]

    - role: os-update
      tags: [os, os-update]

    - role: os-upgrade
      tags: [os, os-upgrade]

    - role: os-packages
      tags: [os, os-packages]

    - role: os-shell
      tags: [os, os-shell]

    - role: dev-spacemacs
      tags: [dev, dev-spacemacs]
      when: with_spacemacs | default(False)

    - role: dev-sublime-text
      tags: [dev, dev-sublime-text]
      when: with_sublime_text | default(False)

    - role: dev-vscode-extensions
      tags: [dev, dev-vscode-extensions]
      when: with_vscode_extensions | default(False)
