---
- hosts: localhost
  vars_files:
    - vars/config.yml
    - vars/config_{{ ansible_distribution | lower }}.yml
  roles:
    - role: dotfiles
      tags: dotfiles

    - role: os-configure
      tags: [os, os-configure]

    - role: os-update
      tags: [os, os-update]

    - role: os-upgrade
      tags: [os, os-upgrade]

    - role: os-packages
      tags: [os, os-packages]
      when: with_packages | default(False)

    - role: os-shell
      tags: [os, os-shell]
      when: with_packages | default(False)

    - role: os-kitty
      tags: [os, os-kitty]
      when: with_packages | default(False)

    - role: dev-rust
      tags: [dev, dev-rust]
      when: with_rust | default(False)
