---
- name: Clone the spacemacs repository
  git:
    repo: '{{ spacemacs_url }}'
    dest: '{{ spacemacs_repo }}'
    version: '{{ spacemacs_branch }}'
    clone: yes
    force: yes
    depth: 1

# First pass installs initial packages and performs an update.
- name: First pass for spacemacs packages
  command: "emacs --batch --user {{ ansible_user }} --kill --eval '(configuration-layer/update-packages t)'"

# Second pass install all packages that were queued to update by the first pass.
- name: Second pass for spacemacs packages
  command: "emacs --batch --user {{ ansible_user }} --kill --eval '(configuration-layer/update-packages t)'"

# Third pass ensures everything went well in the second pass.
- name: Third pass for spacemacs packages
  command: "emacs --batch --user {{ ansible_user }} --kill"
