gui:
  scrollHeight: 10
  mouseEvents: false
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    externalDiffCommand: "difft --color=always"

  commitPrefix:
    pattern: "^\\w+\\/(\\w+-\\w+).*"
    replace: "[$1] "

  branchPrefix: "jswierk/"

os:
  # edit: "emacsclient --tty {{filename}}"
  # editAtLine: "emacsclient --tty +{{line}} {{filename}}"
  editPreset: "helix"

disableStartupPopups: true
promptToReturnFromSubprocess: false

keybinding:
  universal:
    nextScreenMode: "="
    prevScreenMode: "-"
