---
- name: Check if VSCode exists
  stat:
    path: /usr/bin/codium
  register: code_installed

- block:
  - name: List already installed VSCode extensions
    command: 'codium --list-extensions'
    register: code_extensions
    changed_when: False

  - name: Install VSCode extensions
    command: 'codium --install-extension {{ item }}'
    with_items: '{{ vscode_extensions }}'
    register: code_output
    changed_when: '"is already installed" not in code_output.stdout'
    when: 'item not in code_extensions.stdout'

  when: code_installed.stat.executable is defined and code_installed.stat.executable
